# path related
# data_dir: C:/Users/David/PythonProjects/ProgrammingWork/FFHNet-dev/data/robotiq_data_v1.0 # path to dataset
# data_dir: /home/david.martinez/grasp_experiments/Multifinger-Net-dev/data/robotiq_data_v1.0 # path to dataset
data_dir: /workspaces/inference_container/Multifinger-Net-dev/data/robotiq_data_v2.0_full # path to dataset
# data_dir: /data/net/userstore/david.martinez/robotiq_data_v2.0_full # path to dataset
# data_dir: /home/dm/panda_ws/inference_container/Multifinger-Net-dev/data/robotiq_data_v2.0_full # path to dataset
load_path:  # in case continue training otherwise leave empty
gazebo_obj_path: /home/dm/panda_ws/gazebo-objects/objects_gazebo

# train/eval mode
model: ffhnet # either ffhnet or pointnet
model_name:  # cooresponding to the class name of the model. Have to also change the import class name in the script.
name: ffhgan_lr_0.0001_bs_1000 # name saved as checkpoint
continue_train: false # true for loading model from load_path, otherwise start from 1 epoch.
load_epoch: 1
is_train: true
is_group_joints: false
ds_name: train
grasp_data_file_name: grasp_data_all.h5
gpu_ids:
  - 0
num_threads: 16
train_ffhevaluator: false
train_ffhgenerator: true
eval_ffhevaluator: false
eval_ffhgenerator: true
vis_grasp_refinement: false

# log
print_freq: 100 # times to print within one epoch
save_freq: 3 #1 for vae
save_latest_freq: 1
to_tensorboard: true

# model hyper param
n_hand_joints: 12
batch_size: 32
beta1: 0.9
bce_weight: 1 # 10 for ffhnet
init_gain: 0.02
kl_coef: 0.005
latentD: 5
lr: 0.0001
lr_policy: plateau
num_bps_per_object: 5
num_epochs: 90 # 30 vae
# num_epochs: 30
patience_lr_policy_plateau: 3
scale: 1
threshold_lr_policy_plateau: 0.01
weight_decay: 0.0005
weight_init_type: xavier

# Only for GAN:
is_wgan: false # select Wasserstein GAN
gen_train_freq : 1 
lr_dis: 0.0001 #lr for discriminator
lr_gen: 0.0001 #lr for generator