batch_size: 2048
beta1: 0.9
ckpts_dir: /data-r10/qf/ffhnet/checkpoints
continue_train: false
data_dir: /data-r10/qf/hithand_data/new_data_full/
ds_name: train
eval_dir: null
eval_ffhcolldetr: true
eval_ffhevaluator: false
eval_ffhgenerator: false
gpu_ids:
- 1
grasp_data_file_name: grasp_data_all.h5
init_gain: 1
is_train: true
kl_coef: 0.005
latentD: 5
load_path: /data-r10/qf/ffhnet/checkpoints/2023-02-14T21_26_43
lr: 1.0e-06
lr_policy: plateau
model: ffhnet
name: ffhnet_lr_1e-06_bs_2048_scale_1_latentd_5
num_bps_per_object: 5
num_epochs: 30
num_threads: 10
patience_lr_policy_plateau: 3
print_freq: 1
save_dir: /data-r10/qf/ffhnet/checkpoints/2023-02-17T11_49_48
save_freq: 1
save_latest_freq: 1
scale: 1
start_epoch: 0
threshold_lr_policy_plateau: 0.01
to_tensorboard: true
train_ffhcolldetr: true
train_ffhevaluator: false
train_ffhgenerator: false
vis_grasp_refinement: false
weight_decay: 0.0005
weight_init_type: xavier
